### ISSUE TITLE
The instruments are a bit off starting with the second loop

### ISSUE THREAD

**Issue by RetingencyPlan** [superctr/QuattroPlay#1]
So, after playing the first loop(a.k.a. the first 4 minutes) the instruments start sounding a bit off...
Maybe ridgerac2 has this only issue but it could be evident in others as well...
[ridgera2_051.zip](https://github.com/superctr/QuattroPlay/files/450618/ridgera2_051.zip)

**Comment by superctr** [comment]
it's a problem in the original sound data. see [notes](https://github.com/superctr/QuattroPlay/blob/master/ini/ridgera2.ini#L29)
