### ISSUE TITLE
F11 logging doesn't output 4 channels

### ISSUE THREAD

**Issue by RingoStarr39** [superctr/QuattroPlay#10]
I just noticed this. Logging with F11 will only output 2 channels, with the 4 quad channels getting mixed down. Before all 4 channels were output separately.
I used the 4 channel test tones from Cyber Commando to test this, see attached file.
[qp_log.zip](https://github.com/superctr/QuattroPlay/files/3118067/qp_log.zip)

**Comment by superctr** [comment]
It's because the mixdown happens before the wav output, see [here](https://github.com/superctr/QuattroPlay/blob/master/src/audio.c#L63-L95). I agree this behavior is unexpected.

Mixdown is forced if the program was unable to open an audio device with 4 channels. This sometimes happens on windows, depending on the sound card and audio device settings.

**Comment by RingoStarr39** [comment]
I'm using the same sound device I used before, (a Behringer UMC204HD interface) and it's still getting mixed down to 2 channels. It would be nice to have a way of overriding the mixdown behavior.
Also, will it ever be possible for the program to have true surround sound playback? Like for example when connected to a multichannel amp with HDMI or an optical cable? It would be cool to be able to hear the way those few surround sound games originally sounded.

**Comment by superctr** [comment]
Quattroplay always first attempts to open the sound device using 4 channels, if this fails it will attempt opening with 2 channels and do mixdown. So if you have 4 speakers and it is configured correctly, you might already get 4.0 surround sound. One thing I have considered is binaural surround with stereo output, but I would need to find a good (and preferably non-patented and easy to implement) algorithm for that.

**Comment by RingoStarr39** [comment]
I tried starting the program when connected to a 5.1 system with HDMI and the program would still only output in stereo PCM. There was no multichannel output. In fact, when the receiver was in multichannel mode from another program I couldn't even select a game.

**Comment by superctr** [comment]
I think if it fails to open the audio device with 4 channels even if you have selected a 5.1 device, it could be a bug in SDL, in which case there is not much I can do about it. You can try setting SDL's audio interface with the "SDL_AUDIODRIVER" environment variable. On both my development PCs, running Windows 7 and Linux, 4-channel audio works fine using dsound and pulseaudio respectively.

**Comment by RingoStarr39** [comment]
A new update: I now have a better Denon receiver with HDMI that can decode up to 7.1.
When I use Quattroplay while I'm connected to the receiver with HDMI, the software outputs summed mono audio to all 8 (!) channels. For example, the speaker tests in games like Cyber Commando and Tokyo Wars play the same audio in all of the speakers; there's no left/right or front/rear separation at all. I confirmed this with F11 logging as it now logs the same mono audio to 8 channels. Is there anyway the software could be updated to properly use the correct channels in a 5.1 or 7.1 environment?

**Comment by superctr** [comment]
Please paste console output. It sounds like SDL is failing to open the device with 2 channels. Or in this case, returning a stream handle with only 1 channel. I think in this case you should probably report the bug to SDL developers. A 7.1 device should at least be able to handle a stereo stream.

As for the F11 logging, it just logs whatever is sent to the audio stream. That is why you won't get all 4 channels if SDL opens a stream with fewer channels.

Something you could try (on Windows) is to use [VB-cable ](https://www.vb-audio.com/Cable/)or [Virtual Audio Cable](https://vac.muzychenko.net/en/) and run QP through that. Unfortunately, they are not free.

**Comment by RingoStarr39** [comment]
How would I go about obtaining the console output? I'm not familiar with MSYS at all.
Also, reporting such a bug (if it is a bug) to the developers is probably outside of my scope.
I thought it would be interesting to be able to hear the 4 channel games in their native surround format but this seems like more trouble than it's worth.

**Comment by superctr** [comment]
You need to compile the program with "make clean && make DEBUG=1". Then just launch the program from the command line; depending on if you use bash or cmd it's "bin/QuattroPlay" or "bin\QuattroPlay.exe".

When you select a game it will print debug info to the standard output. You can then highlight that and copy.

In MSYS bash it's ctrl+insert to copy. in CMD you have to rightclick the logo on the top left, Edit->Mark to activate highlighting, then press enter to copy).

Again I'm sorry you're not able to use 4 channel output. On windows you're entirely at the mercy of whoever wrote the sound card driver if it works or not. On Linux/Mac the 4-channel output and logging always works, AFAIK.

**Comment by RingoStarr39** [comment]
I finally figured out what the culprit was. If you have the surround format configured as 5.1 or 7.1 in Windows, the program doesn't know how to allocate the channels properly. You have to set up the surround format as "Quadraphonic" to get the front and rear channels mapped properly. Then F11 logging does work as intended.
