### ISSUE TITLE
Time Crisis 1 Doesn't Sound Right And Outdated

### ISSUE THREAD

**Issue by kim-sama** [superctr/QuattroPlay#15]
The audio quality for Time Crisis 1 is outdated and doesn't sound the same are the current version of Mame and real hardware, like some samples sounding totally different. Seems to doesn't have that bass or something. I tried switching Stereo to Quad but it doesn't do anything.

**Comment by superctr** [comment]
It's because one of the sample roms are byteswapped. You can fix it with dd or romwak.

**Comment by kim-sama** [comment]
I could use romwak but I don't know how to do it and I can't seem to find dd

**Comment by kim-sama** [comment]
Wait, I think I fixed it. Romwak did work
