### ISSUE TITLE
Issue with the make process

### ISSUE THREAD

**Issue by b0x-Cub3d** [superctr/QuattroPlay#16]
Environment for Compiling: MSYS2 64/32-bit

I have all the dependencies you've listed on your readme, and I ran make in the directory. It compiled the source files fine, but it fails on linking the files properly to create the executable. Here's the log:
https://mega.nz/file/rOhE2S6Z#Vf4r8eR2G55kc2jalN5C0RA-xRAzglmLwB4kqS8q8z8

**Comment by superctr** [comment]
see https://github.com/superctr/QuattroPlay/issues/14#issuecomment-797299288
