### ISSUE TITLE
A few updated ini files & minor issue

### ISSUE THREAD

**Issue by RingoStarr39** [superctr/QuattroPlay#3]
I've updated a few of the ini files with more complete and accurate information.
Also, I just wanted to let you know that the percussion channels in C219 games have the stereo image reversed for some reason. I noticed it when I was recording the music for Emeraldia compared to the Wii Virtual Console version.

[quattroplay ini files.zip](https://github.com/superctr/QuattroPlay/files/1605574/quattroplay.ini.files.zip)

**Comment by superctr** [comment]
Fixed the C219 issue. I'll take a look at the ini files later.
