### ISSUE TITLE
Cyber Cycles Demo looping

### ISSUE THREAD

**Issue by RingoStarr39** [superctr/QuattroPlay#4]
Is there anyway to make the track "Demo" from Cyber Cycles correctly loop and then end like it does in the Namco Game Sound Express soundtrack? Or are those loops not in the game data? I also noticed a similar issue with the track "Shallows" from Aqua Rush. It doesn't loop correctly either. You can hear how it's supposed to sound on the iTunes Namco Sounds soundtrack.

**Comment by superctr** [comment]
There are many cases where they lengthened or arranged the songs in the
soundtrack release. Sometimes there is unused song data and I try to find
and patch the data to play those parts. But I checked both of the songs you
mentioned and in both cases there are no unused parts in the data.

Den 1 mars 2018 00:40 skrev "RingoStarr39" <notifications@github.com>:

**Comment by RingoStarr39** [comment]
Okay. I thought that might be the case. Thanks for looking into it.

btw, I updated the .ini file for Rompers with some more accurate titles and added a few tracks that were missing: 
[rompers.zip](https://github.com/superctr/QuattroPlay/files/1809255/rompers.zip)
