### ISSUE TITLE
ini changes

### ISSUE THREAD

**Issue by RingoStarr39** [superctr/QuattroPlay#8]
I've made some improvements to a few ini files which I've attached and explained below:

Assault: I rearranged the tracks to match all of the official soundtracks. I also added Unused Track 3 and Unused Track 4 which not many know about. Unfortunately these tracks' YM2151 and C140 parts are separated and I don't know how to configure the ini to play them both simultaneously, if that's even possible. I also noticed a problem with the snares in "Lift Down". There are three identical snare samples playing on three channels that are supposed to be slightly out of phase which changes the sound. Compare to official soundtracks and PCB recordings.
Cosmo Gang the Video: Changed some track titles with better translations.
Mr. Driller: I rearranged the order of the tracks to more closely represent the order that they're heard in-game.
Namco Classic Collection Vol.1: I rearranged and renamed most of the tracks to better match the Wonder Spirits soundtrack CD, except where that CD had some mistakes. I removed the track names for Xevious Arrangement since those names are meant solely for the arranged versions on Xevious 3D/G+.
Namco Classic Collection Vol.2: Pretty much the same as Vol.1.
Ordyne: Rearranged tracks according to iTunes soundtrack and corrected some titles.
Return of Ishtar: Corrected track names and added clear fanfare.
Rompers: Fixed some of the track names that were incorrect.
[12-09-19 ini changes.zip](https://github.com/superctr/QuattroPlay/files/2661576/12-09-19.ini.changes.zip)

**Comment by superctr** [comment]
It's easier for me to review the changes if you send a pull request instead.
